name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AWS_REGION: 'ap-southeast-1'
  S3_BUCKET: 's3://fe-studio.gosh.com/antdMobile'
  DIST_PATH: './dist'

jobs:
  build:
    if: github.repository == 'goshgame/ant-design-mobile'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Build docs
        run: npm run build-doc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync Static files to S3
        run: aws s3 sync $DIST_PATH $S3_BUCKET --delete

  skipped:
    if: github.repository != 'goshgame/ant-design-mobile'
    runs-on: ubuntu-latest
    steps:
      - name: Skip deployment
        run: echo "Skipped deployment - this is a fork, only main repo runs deploy."
